### ISSUE TITLE
Modern black and white icons

### ISSUE THREAD

**Issue by FlashSystems** [kpcyrd/arch-audit-gtk#4]
Thank you for this great utility. I've created a set of icons to get the look a little more in line with the current black and white style of the gnome status bar. I haven't currently ested them on KDE or i3. What do you think of them? Is there a chance to include them in the package (maybe as an option)?

If you like them, I would be happy to create a pull request containing the SVG files.

This is how it looks on the gnome3 status bar:
![screenshot](https://user-images.githubusercontent.com/10105345/113909713-49186e00-97d8-11eb-8482-660ffaacbca2.png)

The different icons look like this. They work well on a light or dark background.
* No updates (check.svg) \
  ![check](https://user-images.githubusercontent.com/10105345/113910187-d52a9580-97d8-11eb-9ee6-d02ddf1e60d9.png)
* Updates available (alert.svg) \
  ![alert](https://user-images.githubusercontent.com/10105345/113910123-c47a1f80-97d8-11eb-8719-c5649b103152.png)
* Error (cross.svg) \
  ![cross](https://user-images.githubusercontent.com/10105345/113909957-93015400-97d8-11eb-88c9-a68696c1f8d3.png)

**Comment by kpcyrd** [comment]
Wow, looks awesome!

I'd definitely like to have them as an option, I'm just not sure what's the best way to add theming because this is my first gtk project. If you happen to have any pointers those would be greatly appreciated!

Feel free to simply PR the svgs into `icons/<themename>/` and I write the code later. If you could make the shield in the `check` icon green and the shield in the `alert` icon yellow I'd take that as a second theme and probably make them the default.

Thanks!
